
CREATE OR REPLACE FUNCTION FUN_DB_CALCULA_VL_TOT_VENDA( P_ANO_VENDA IN NUMBER) RETURN NUMBER
IS
-- VARIÁVEL DO TIPO DE DADO DA COLUNA, POIS VAMOS
-- REALIZAR CÁLCULO SOBRE ELA.
V_VL_TOT_VENDA DB_PEDIDO.VL_TOT_PEDIDO%TYPE;
BEGIN
    SELECT  SUM(VL_TOT_PEDIDO) VAL_TOT_VENDA
    INTO    V_VL_TOT_VENDA
    FROM    DB_PEDIDO
    WHERE   EXTRACT( YEAR FROM DT_PEDIDO) = P_ANO_VENDA;
    
    IF V_VL_TOT_VENDA IS NULL THEN
        V_VL_TOT_VENDA := 00;
    END IF;
    
    -- RETORNANDO A VARIÁVEL COM O CÁLCULO REALIZADO
    RETURN V_VL_TOT_VENDA;
EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR (-20010, 'ERRO CRÍTICO NA FUNÇÃO FUN_DB_CALCULA_VL_TOT_VENDA ' || SQLERRM);
		
END FUN_DB_CALCULA_VL_TOT_VENDA;
/